language: ruby
rvm:
  - 2.2.9
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
env:
  - "RAILS_VERSION=master"
  - "RAILS_VERSION=5.1.0"
  - "RAILS_VERSION=5.2.0"
matrix:
  allow_failures:
    - rvm: ruby-head
    - env: RAILS_VERSION=master
sudo: false
