language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx
env:
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.2.0"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
