version: '2'
services:
  lib:
    command: rspec
    image: sticksnleaves/ruby-project:2.5
    volumes:
      - .:/usr/src/app
      - lib.volume:/usr/local/bundle
volumes:
  lib.volume:
    driver: local
