name: ci

on: [push, pull_request]

jobs:
  test:
    if: github.actor != 'dependabot[bot]' && github.event_name == 'push' ||
      github.event_name == 'pull_request'

    strategy:
      matrix:
        rails: ["6.1", "7.0", "7.1", "master"]
        ruby: ["3.0", "3.1", "3.2"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install \
            build-essential \
            libsqlite3-dev

      - name: Install bundler
        run: gem install bundler

      - env:
          RAILS_VERSION: ${{ matrix.rails }}
        name: Install dependencies
        run: bundle install

      - env:
          RAILS_VERSION: ${{ matrix.rails }}
        name: Test
        run: bundle exec rspec
