name: ci

on: [push, pull_request]

jobs:
    test:
        strategy:
            matrix:
                rails: ['5.2', '6.0', '6.1', '7.0', 'master']

                ruby: ['2.6', '2.7', '3.0', '3.1']

                exclude:
                    - rails: master

                      ruby: '2.6'

                    - rails: '7.0'
                    
                      ruby: '2.6'

                    - rails: '7.0'
                    
                      ruby: '3.1'

                    - rails: '6.0'

                      ruby: '3.0'

                    - rails: '6.0'

                      ruby: '3.1'

                    - rails: '5.2'

                      ruby: '2.7'

                    - rails: '5.2'

                      ruby: '3.0'

                    - rails: '5.2'

                      ruby: '3.1'

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: ruby/setup-ruby@v1
            
              with:
                  ruby-version: ${{ matrix.ruby }}

            - name: Install toolchain

              run: |
                  sudo apt-get update

                  sudo apt-get install \
                    build-essential \
                    libsqlite3-dev

            - name: Install bundler

              run: gem install bundler

            - env:
                  RAILS_VERSION: ${{ matrix.rails }}
            
              name: Install dependencies

              run: bundle install

            - env:
                  RAILS_VERSION: ${{ matrix.rails }}

              name: Test

              run: bundle exec rspec

                